name: CI/CD – Micro Product Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_PROJECT_NAME: product_app
  APP_CONTAINER_NAME: product_app_2025
  SONAR_PROJECT_KEY: product-app
  SONAR_HOST_URL: http://localhost:9000
  SONAR_TOKEN: squ_33084de8926870c4009b98cd0dc14b879dd8641c

jobs:
  build_analyze_deploy:
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v4

      - name: ☕ Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: ⚙ Construir el .jar con Maven
        run: mvn clean package -DskipTests

      - name: 📊 Análisis con SonarQube
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_TOKEN }}

      - name: 🚀 Despliegue con Docker Compose
        run: |
          echo "🔧 Desplegando aplicación..."
          cd docker
          docker-compose -p $DOCKER_PROJECT_NAME down -v --remove-orphans || true
          docker-compose -p $DOCKER_PROJECT_NAME up -d --build
          echo "📋 Logs recientes:"
          docker logs --tail 50 $APP_CONTAINER_NAME
